### ISSUE TITLE
Demo failed

### ISSUE THREAD

**Issue by superaha** [yoxu515/aot-benchmark#2]
Hello , thank you for making this repo public. I am trying to run the demo, which raises the following error:

 `
Object number: 44. Inference size: 577x1041. Output size: 1080x1920.
/opt/miniconda/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272126608/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
./networks/layers/position.py:63: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_pos_feats)
Traceback (most recent call last):
  File "tools/demo.py", line 289, in <module>
    main()
  File "tools/demo.py", line 285, in main
    demo(cfg)
  File "tools/demo.py", line 204, in demo
    obj_nums=obj_nums)
  File "./networks/engines/aot_engine.py", line 586, in add_reference_frame
    img_embs=img_embs)
  File "./networks/engines/aot_engine.py", line 239, in add_reference_frame
    size_2d=self.enc_size_2d)
  File "./networks/models/aot.py", line 105, in LSTT_forward
    pos_emb, size_2d)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./networks/layers/transformer.py", line 100, in forward
    size_2d=size_2d)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./networks/layers/transformer.py", line 224, in forward
    tgt3 = self.short_term_attn(local_Q, local_K, local_V)[0]
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./networks/layers/attention.py", line 471, in forward
    output = agg_value + agg_bias
RuntimeError: The size of tensor a (32) must match the size of tensor b (256) at non-singleton dimension 3.
`
Can you help fix this error?
Thanks!

**Comment by z-x-yang** [comment]
Done. Please try again.
