### ISSUE TITLE
No module named spatial_correlation_Sampler

### ISSUE THREAD

**Issue by sivaji123256** [yoxu515/aot-benchmark#40]
Hi @z-x-yang ,
It was mentioned in the readme that demo script will run even without spatial correlation sampler.But, in the attention.py ,it was being imported and the error is as follows:

Build AOT model.
Traceback (most recent call last):
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/tools/demo.py", line 286, in <module>
    main()
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/tools/demo.py", line 282, in main
    demo(cfg)
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/tools/demo.py", line 107, in demo
    model = build_vos_model(cfg.MODEL_VOS, cfg).cuda(gpu_id)
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/./networks/models/__init__.py", line 7, in build_vos_model
    return AOT(cfg, encoder=cfg.MODEL_ENCODER, **kwargs)
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/./networks/models/aot.py", line 23, in __init__
    self.LSTT = LongShortTermTransformer(
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/./networks/layers/transformer.py", line 75, in __init__
    block(d_model, self_nhead, att_nhead, dim_feedforward,
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/./networks/layers/transformer.py", line 279, in __init__
    self.short_term_attn = MultiheadLocalAttention(d_model,
  File "/home/ubuntu/sam_track/DeAOT/aot-benchmark/./networks/layers/attention.py", line 282, in __init__
    from spatial_correlation_sampler import SpatialCorrelationSampler
ModuleNotFoundError: No module named 'spatial_correlation_sampler

**Comment by yoxu515** [comment]
Hello, we have update our code, and now you can try running the code without spatial_correlation_sampler. If you still have problem, please let me know.

**Comment by bhack** [comment]
What is the perf gap without spatial correlation sampler?

**Comment by z-x-yang** [comment]
Closing as resolved/stale; the code has since been updated to avoid this dependency issue.
